syrashid/rails-baybe

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
we have button style and changed body background color and font-family
> button style - body background color - font-family

- Gemfile
- Gemfile.lock
- app/models/photo.rb
- app/models/user.rb
- app/uploaders/photo_uploader.rb
- db/migrate/20190820142209_change_url_to_photolink.rb
- db/schema.rb
Please make sure to bundle install, as I've added a couple of gems for cloudinary
> FEAT: Added cloudinary to Photo and User Models

- app/controllers/categories_controller.rb
- app/controllers/products_controller.rb
- app/views/categories/index.html.erb
- app/views/products/index.html.erb
- config/routes.rb
- test/controllers/categories_controller_test.rb
- test/controllers/products_controller_test.rb
created products - controller and view files and added router
created categories controller and categories-view files
> Seach items

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar_with_search.html.erb
FIX: Finished navbar, created global variables for colors and other styling things
> FIX: Finished navbar, created global variables for colors and other styling things

- app/assets/stylesheets/products/_product.scss
- app/controllers/products_controller.rb
- app/views/products/show.html.erb
changed classname,added default age,condition,color arrays, finished  show page
> last version

- app/controllers/boxes_controller.rb
- app/views/boxes/index.html.erb
- db/seeds.rb
boxes controller added index method, created boxes review view and created seed files for boxes
> boxes review

- .idea/.gitignore
- .idea/misc.xml
- .idea/modules.xml
- .idea/rails-baybe.iml
- .idea/vcs.xml
- db/seeds.rb
> fix:fixed the ratio

- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/products_controller.rb
- app/views/products/_filter_bar.html.erb
- app/views/products/index.html.erb
Also refactored the filterbar so we can render it
> FIX: Changed filter to links to all products and added style

- app/models/product.rb
- app/views/shared/_new_product_form.html.erb
> Worked in the form style CSS and added the price for the admin

- app/controllers/carts_controller.rb
- app/views/carts/show.html.erb
Reverts syrashid/rails-baybe#74
> Revert "FEAT: Changed button functionality when no items in cart"

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_chadainer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_nicontainer.scss
- app/javascript/components/popover.js
- app/javascript/packs/application.js
- app/views/carts/index.html.erb
- app/views/carts/show.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
> Edit profile

- app/controllers/carts_controller.rb
- app/models/cart.rb
- app/models/user.rb
- app/views/carts/index.html.erb
- app/views/carts/show.html.erb
- app/views/shared/_navbar_with_search.html.erb
Issue was caused by the caching behavior of rails when using relations such as has_many.  Changed over to a direct sql call through find_by to bypass caching behavior
> FIX: Multiple Cart Creation Issue

- app/assets/stylesheets/components/_dropdown.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/models/cart.rb
- app/views/shared/_navbar.html.erb
- app/views/shared/_navbar_for_selling.html.erb
- app/views/shared/_navbar_with_search.html.erb
- db/schema.rb
Also changed the footer padding to 20vh instead of 50vh
> Navbar dropdown style

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/views/shared/_searchbar.html.erb
- Made the searchbar responsive, I need to make the navbar responsive so it works on all pages
- Had to change the banner padding to help with the responsiveness
- Putted searchbar in a separate scss file
> FIX: Made searchbar responsive

- app/assets/stylesheets/carts/_cart_confirm.scss
- app/assets/stylesheets/carts/_index.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/payments/_index.scss
- app/views/boxes/current.html.erb
- app/views/boxes/show.html.erb
- app/views/carts/current.html.erb
- app/views/carts/index.html.erb
- app/views/carts/show.html.erb
Part 1 of Many Pull Request to remove Bootstrap.
This portion included the following files
views > boxes
-current.html.erb
-index.html.erb
-show.html.erb
views > carts
-current.html.erb
-index.html.erb
-show.html.erb
> Remove bootstrap

- app/assets/stylesheets/components/_baybecontainer.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/products/_product.scss
- app/views/shared/_product_info.html.erb
- Created a w-lx for a 90% with on the baybecontainer
- Moved the conditions and add to cart buttons to the right section
- Made everything in the product info responsive
> FIX: Fix product info card responsiveness

- app/assets/stylesheets/boxes/_index.scss
- app/assets/stylesheets/carts/_cart_confirm.scss
- app/assets/stylesheets/components/_baybecontainer.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/products/_product.scss
- app/views/carts/show.html.erb
- app/views/shared/_filter_bar.html.erb
- app/views/shared/_product_info.html.erb
Changed the category items to a ul and made them responsive
> FIX: Catfilter responsive

- app/assets/stylesheets/boxes/_index.scss
- app/assets/stylesheets/carts/_cart_confirm.scss
- app/assets/stylesheets/components/_baybecontainer.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/products/_product.scss
- app/javascript/components/delivery_form.js
- app/javascript/packs/application.js
- app/views/carts/current.html.erb
- app/views/carts/show.html.erb
- app/views/shared/_filter_bar.html.erb
- app/views/shared/_product_info.html.erb
Added JS so when the "home" is selected in the address form the input fields are disabled (they are enabled when the Delivery Address is selected).
> FEAT: Disable/enable Address Form

- app/assets/stylesheets/boxes/_index.scss
- app/assets/stylesheets/carts/_cart_confirm.scss
- app/assets/stylesheets/carts/_index.scss
- app/assets/stylesheets/components/_baybecontainer.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/products/_product.scss
- app/javascript/components/delivery_form.js
- app/javascript/packs/application.js
- app/views/carts/current.html.erb
- app/views/carts/index.html.erb
- app/views/carts/show.html.erb
- app/views/shared/_filter_bar.html.erb
- app/views/shared/_product_info.html.erb
- Change the bootstrap col settings on current and added it to the orders list. 
- Used similar setup for order list than I used for Current Cart responsiveness, also added some changes (hidding and showing elements) on the smaller screen.
> FIX: Orders list responsiveness

- app/assets/stylesheets/boxes/_index.scss
- app/assets/stylesheets/carts/_cart_confirm.scss
- app/assets/stylesheets/carts/_index.scss
- app/assets/stylesheets/components/_baybecontainer.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/products/_product.scss
- app/javascript/components/delivery_form.js
- app/javascript/packs/application.js
- app/views/carts/current.html.erb
- app/views/carts/index.html.erb
- app/views/carts/show.html.erb
- app/views/shared/_filter_bar.html.erb
- app/views/shared/_product_info.html.erb
It still don't show the confirmation message but it's now working on both pages (current and show) and on both pages it reloads automatically (no need to refresh).
> FIX: Fixed delete buttons from the cart show

- app/controllers/products_controller.rb
- app/controllers/sell_products_controller.rb
- app/views/products/filtercategory.js.erb
- app/views/products/filtercondition.js.erb
- app/views/shared/_filter_bar.html.erb
Need to discuss possible solution with you so I put in a temp fix for now
> Dual filters

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_dropdown.scss
- app/assets/stylesheets/components/_navbar.scss
- app/helpers/application_helper.rb
- app/views/boxes/current.html.erb
- app/views/boxes/show.html.erb
- app/views/carts/current.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/applicationseller.html.erb
- app/views/sell_products/show.html.erb
- app/views/shared/_navbar_for_selling.html.erb
- app/views/shared/_product_info_sell.html.erb
- app/views/shared/_searchbarforsell.html.erb
Changed the theme helper and now everything is rendered from a particular seller/buyer view, had to create some classes to add to the seller views
> FIX: conditional classes

- app/assets/stylesheets/products/_sell_product.scss
- app/controllers/products_controller.rb
- app/controllers/sell_products_controller.rb
- app/views/sell_products/_sell_product_card_partial.html.erb
- app/views/shared/_new_product_form.html.erb
We're going to have a nice long laugh about this tomorrow
> Update color newproduct

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/views/shared/_searchbar.html.erb
Fixed responsiveness: 
- Navbar
- Current and index pages of boxes/carts
- Searchbar (had a border radius on mobile but not on web)
- Filters
> FIX: Fix responsiveness
